#!/usr/bin/env python

from src.ohce.kata import OhceKata, Clock

def run(name):
    clock = Clock()
    ohce_kata = OhceKata(clock)
    ohce_kata.run(name)


if __name__ == '__main__':
    import sys
    args = sys.argv[1:]
    run(args[0])
